/* Generated by re2c 0.16 */
#line 1 "implicit.re"
#include "yaml.h"

yaml_char_t *
find_implicit_tag(str, len)
  const yaml_char_t *str;
  size_t len;
{
  /* This bit was taken from implicit.re, which is in the Syck library.
   *
   * Copyright (C) 2003 why the lucky stiff */

  const yaml_char_t *cursor, *limit, *marker;
  cursor = str;
  limit = str + len;


#line 20 "implicit.c"
{
	yaml_char_t yych;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '+':	goto yy6;
	case '-':	goto yy7;
	case '.':	goto yy8;
	case '0':	goto yy9;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy10;
	case '<':	goto yy11;
	case '=':	goto yy12;
	case 'F':	goto yy13;
	case 'N':	goto yy14;
	case 'O':	goto yy15;
	case 'T':	goto yy16;
	case 'Y':	goto yy17;
	case 'f':	goto yy18;
	case 'n':	goto yy19;
	case 'o':	goto yy20;
	case 't':	goto yy21;
	case 'y':	goto yy22;
	case '~':	goto yy23;
	default:	goto yy4;
	}
yy2:
	++cursor;
#line 60 "implicit.re"
	{   return (yaml_char_t *)"null"; }
#line 58 "implicit.c"
yy4:
	++cursor;
yy5:
#line 106 "implicit.re"
	{   return (yaml_char_t *)"str"; }
#line 64 "implicit.c"
yy6:
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':	goto yy24;
	case '0':	goto yy26;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy27;
	default:	goto yy5;
	}
yy7:
	yych = *(marker = ++cursor);
	switch (yych) {
	case '.':	goto yy29;
	case '0':	goto yy26;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy27;
	default:	goto yy5;
	}
yy8:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'I':	goto yy30;
	case 'N':	goto yy31;
	case 'i':	goto yy32;
	case 'n':	goto yy33;
	default:	goto yy5;
	}
yy9:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:	goto yy34;
	case ',':	goto yy36;
	case '.':	goto yy38;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy40;
	case '8':
	case '9':	goto yy41;
	case ':':	goto yy42;
	case 'x':	goto yy43;
	default:	goto yy5;
	}
yy10:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:	goto yy34;
	case ',':	goto yy27;
	case '.':	goto yy38;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy44;
	case ':':	goto yy42;
	default:	goto yy5;
	}
yy11:
	yych = *(marker = ++cursor);
	switch (yych) {
	case '<':	goto yy45;
	default:	goto yy5;
	}
yy12:
	yych = *++cursor;
	if (yych <= 0x00) goto yy46;
	goto yy5;
yy13:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'A':	goto yy48;
	case 'a':	goto yy49;
	default:	goto yy5;
	}
yy14:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:	goto yy50;
	case 'O':
	case 'o':	goto yy52;
	case 'U':	goto yy53;
	case 'u':	goto yy54;
	default:	goto yy5;
	}
yy15:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'F':	goto yy55;
	case 'N':
	case 'n':	goto yy56;
	case 'f':	goto yy57;
	default:	goto yy5;
	}
yy16:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'R':	goto yy58;
	case 'r':	goto yy59;
	default:	goto yy5;
	}
yy17:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:	goto yy60;
	case 'E':	goto yy62;
	case 'e':	goto yy63;
	default:	goto yy5;
	}
yy18:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy49;
	default:	goto yy5;
	}
yy19:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:	goto yy50;
	case 'o':	goto yy52;
	case 'u':	goto yy54;
	default:	goto yy5;
	}
yy20:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'f':	goto yy57;
	case 'n':	goto yy56;
	default:	goto yy5;
	}
yy21:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'r':	goto yy59;
	default:	goto yy5;
	}
yy22:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 0x00:	goto yy60;
	case 'e':	goto yy63;
	default:	goto yy5;
	}
yy23:
	yych = *++cursor;
	if (yych <= 0x00) goto yy2;
	goto yy5;
yy24:
	yych = *++cursor;
	switch (yych) {
	case 'I':	goto yy30;
	case 'i':	goto yy32;
	default:	goto yy25;
	}
yy25:
	cursor = marker;
	goto yy5;
yy26:
	yych = *++cursor;
	switch (yych) {
	case 0x00:	goto yy34;
	case 'x':	goto yy43;
	default:	goto yy37;
	}
yy27:
	++cursor;
	yych = *cursor;
yy28:
	switch (yych) {
	case 0x00:	goto yy34;
	case ',':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy27;
	case '.':	goto yy38;
	case ':':	goto yy42;
	default:	goto yy25;
	}
yy29:
	yych = *++cursor;
	switch (yych) {
	case 'I':	goto yy66;
	case 'i':	goto yy67;
	default:	goto yy25;
	}
yy30:
	yych = *++cursor;
	switch (yych) {
	case 'N':	goto yy68;
	case 'n':	goto yy69;
	default:	goto yy25;
	}
yy31:
	yych = *++cursor;
	switch (yych) {
	case 'A':
	case 'a':	goto yy70;
	default:	goto yy25;
	}
yy32:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy69;
	default:	goto yy25;
	}
yy33:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy71;
	default:	goto yy25;
	}
yy34:
	++cursor;
#line 76 "implicit.re"
	{   return (yaml_char_t *)"int"; }
#line 309 "implicit.c"
yy36:
	++cursor;
	yych = *cursor;
yy37:
	switch (yych) {
	case 0x00:	goto yy72;
	case ',':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy36;
	case '.':	goto yy38;
	case '8':
	case '9':	goto yy64;
	case ':':	goto yy42;
	default:	goto yy25;
	}
yy38:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy74;
	case ',':	goto yy76;
	case '.':	goto yy78;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy38;
	case 'E':
	case 'e':	goto yy80;
	default:	goto yy25;
	}
yy40:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy81;
	case '8':
	case '9':	goto yy82;
	default:	goto yy37;
	}
yy41:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy82;
	default:	goto yy65;
	}
yy42:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':	goto yy83;
	case '6':
	case '7':
	case '8':
	case '9':	goto yy84;
	default:	goto yy25;
	}
yy43:
	yych = *++cursor;
	if (yych <= 0x00) goto yy25;
	goto yy86;
yy44:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy87;
	default:	goto yy28;
	}
yy45:
	yych = *++cursor;
	if (yych <= 0x00) goto yy88;
	goto yy25;
yy46:
	++cursor;
#line 102 "implicit.re"
	{   return (yaml_char_t *)"default"; }
#line 425 "implicit.c"
yy48:
	yych = *++cursor;
	switch (yych) {
	case 'L':	goto yy90;
	default:	goto yy25;
	}
yy49:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy91;
	default:	goto yy25;
	}
yy50:
	++cursor;
#line 64 "implicit.re"
	{   return (yaml_char_t *)"bool#no"; }
#line 442 "implicit.c"
yy52:
	yych = *++cursor;
	if (yych <= 0x00) goto yy50;
	goto yy25;
yy53:
	yych = *++cursor;
	switch (yych) {
	case 'L':	goto yy92;
	default:	goto yy25;
	}
yy54:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy93;
	default:	goto yy25;
	}
yy55:
	yych = *++cursor;
	switch (yych) {
	case 'F':	goto yy52;
	default:	goto yy25;
	}
yy56:
	yych = *++cursor;
	if (yych <= 0x00) goto yy60;
	goto yy25;
yy57:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy52;
	default:	goto yy25;
	}
yy58:
	yych = *++cursor;
	switch (yych) {
	case 'U':	goto yy94;
	default:	goto yy25;
	}
yy59:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy95;
	default:	goto yy25;
	}
yy60:
	++cursor;
#line 62 "implicit.re"
	{   return (yaml_char_t *)"bool#yes"; }
#line 491 "implicit.c"
yy62:
	yych = *++cursor;
	switch (yych) {
	case 'S':	goto yy56;
	default:	goto yy25;
	}
yy63:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy56;
	default:	goto yy25;
	}
yy64:
	++cursor;
	yych = *cursor;
yy65:
	switch (yych) {
	case ',':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy64;
	case '.':	goto yy38;
	case ':':	goto yy42;
	default:	goto yy25;
	}
yy66:
	yych = *++cursor;
	switch (yych) {
	case 'N':	goto yy96;
	case 'n':	goto yy97;
	default:	goto yy25;
	}
yy67:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy97;
	default:	goto yy25;
	}
yy68:
	yych = *++cursor;
	switch (yych) {
	case 'F':	goto yy98;
	default:	goto yy25;
	}
yy69:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy98;
	default:	goto yy25;
	}
yy70:
	yych = *++cursor;
	switch (yych) {
	case 'N':	goto yy99;
	default:	goto yy25;
	}
yy71:
	yych = *++cursor;
	switch (yych) {
	case 0x00:	goto yy100;
	case '.':	goto yy102;
	case 'n':	goto yy99;
	default:	goto yy25;
	}
yy72:
	++cursor;
#line 70 "implicit.re"
	{   return (yaml_char_t *)"int#oct"; }
#line 567 "implicit.c"
yy74:
	++cursor;
#line 78 "implicit.re"
	{   return (yaml_char_t *)"float#fix"; }
#line 572 "implicit.c"
yy76:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy74;
	case ',':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy76;
	default:	goto yy25;
	}
yy78:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy78;
	case 'E':
	case 'e':	goto yy80;
	default:	goto yy25;
	}
yy80:
	yych = *++cursor;
	switch (yych) {
	case '+':
	case '-':	goto yy103;
	default:	goto yy25;
	}
yy81:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy104;
	case '8':
	case '9':	goto yy105;
	default:	goto yy37;
	}
yy82:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy105;
	default:	goto yy65;
	}
yy83:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy106;
	case '.':	goto yy108;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy84;
	case ':':	goto yy42;
	default:	goto yy25;
	}
yy84:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy106;
	case '.':	goto yy108;
	case ':':	goto yy42;
	default:	goto yy25;
	}
yy85:
	++cursor;
	yych = *cursor;
yy86:
	switch (yych) {
	case 0x00:	goto yy110;
	case ',':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy85;
	default:	goto yy25;
	}
yy87:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy112;
	default:	goto yy28;
	}
yy88:
	++cursor;
#line 104 "implicit.re"
	{   return (yaml_char_t *)"merge"; }
#line 725 "implicit.c"
yy90:
	yych = *++cursor;
	switch (yych) {
	case 'S':	goto yy113;
	default:	goto yy25;
	}
yy91:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy114;
	default:	goto yy25;
	}
yy92:
	yych = *++cursor;
	switch (yych) {
	case 'L':	goto yy115;
	default:	goto yy25;
	}
yy93:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy115;
	default:	goto yy25;
	}
yy94:
	yych = *++cursor;
	switch (yych) {
	case 'E':	goto yy56;
	default:	goto yy25;
	}
yy95:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy56;
	default:	goto yy25;
	}
yy96:
	yych = *++cursor;
	switch (yych) {
	case 'F':	goto yy116;
	default:	goto yy25;
	}
yy97:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy116;
	default:	goto yy25;
	}
yy98:
	yych = *++cursor;
	if (yych <= 0x00) goto yy117;
	goto yy25;
yy99:
	yych = *++cursor;
	if (yych <= 0x00) goto yy119;
	goto yy25;
yy100:
	++cursor;
#line 66 "implicit.re"
	{   return (yaml_char_t *)"bool#na"; }
#line 786 "implicit.c"
yy102:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy121;
	case 'i':	goto yy122;
	case 'r':	goto yy123;
	default:	goto yy25;
	}
yy103:
	yych = *++cursor;
	if (yych <= 0x00) goto yy25;
	goto yy125;
yy104:
	yych = *++cursor;
	switch (yych) {
	case '-':	goto yy126;
	default:	goto yy37;
	}
yy105:
	yych = *++cursor;
	switch (yych) {
	case '-':	goto yy126;
	default:	goto yy65;
	}
yy106:
	++cursor;
#line 72 "implicit.re"
	{   return (yaml_char_t *)"int#base60"; }
#line 815 "implicit.c"
yy108:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case 0x00:	goto yy127;
	case ',':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy108;
	default:	goto yy25;
	}
yy110:
	++cursor;
#line 68 "implicit.re"
	{   return (yaml_char_t *)"int#hex"; }
#line 838 "implicit.c"
yy112:
	yych = *++cursor;
	switch (yych) {
	case '-':	goto yy126;
	default:	goto yy28;
	}
yy113:
	yych = *++cursor;
	switch (yych) {
	case 'E':	goto yy52;
	default:	goto yy25;
	}
yy114:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy52;
	default:	goto yy25;
	}
yy115:
	yych = *++cursor;
	if (yych <= 0x00) goto yy2;
	goto yy25;
yy116:
	yych = *++cursor;
	if (yych <= 0x00) goto yy129;
	goto yy25;
yy117:
	++cursor;
#line 84 "implicit.re"
	{   return (yaml_char_t *)"float#inf"; }
#line 869 "implicit.c"
yy119:
	++cursor;
#line 88 "implicit.re"
	{   return (yaml_char_t *)"float#nan"; }
#line 874 "implicit.c"
yy121:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy131;
	default:	goto yy25;
	}
yy122:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy132;
	default:	goto yy25;
	}
yy123:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy133;
	default:	goto yy25;
	}
yy124:
	++cursor;
	yych = *cursor;
yy125:
	switch (yych) {
	case 0x00:	goto yy134;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy25;
	}
yy126:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy136;
	default:	goto yy25;
	}
yy127:
	++cursor;
#line 82 "implicit.re"
	{   return (yaml_char_t *)"float#base60"; }
#line 930 "implicit.c"
yy129:
	++cursor;
#line 86 "implicit.re"
	{   return (yaml_char_t *)"float#neginf"; }
#line 935 "implicit.c"
yy131:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy137;
	default:	goto yy25;
	}
yy132:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy138;
	default:	goto yy25;
	}
yy133:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy139;
	default:	goto yy25;
	}
yy134:
	++cursor;
#line 80 "implicit.re"
	{   return (yaml_char_t *)"float#exp"; }
#line 958 "implicit.c"
yy136:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy140;
	default:	goto yy25;
	}
yy137:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy141;
	default:	goto yy25;
	}
yy138:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy142;
	default:	goto yy25;
	}
yy139:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy143;
	default:	goto yy25;
	}
yy140:
	yych = *++cursor;
	switch (yych) {
	case '-':	goto yy144;
	default:	goto yy25;
	}
yy141:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy145;
	default:	goto yy25;
	}
yy142:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy146;
	default:	goto yy25;
	}
yy143:
	yych = *++cursor;
	if (yych <= 0x00) goto yy147;
	goto yy25;
yy144:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy149;
	default:	goto yy25;
	}
yy145:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy150;
	default:	goto yy25;
	}
yy146:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy151;
	default:	goto yy25;
	}
yy147:
	++cursor;
#line 90 "implicit.re"
	{   return (yaml_char_t *)"float#na"; }
#line 1045 "implicit.c"
yy149:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy152;
	default:	goto yy25;
	}
yy150:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy153;
	default:	goto yy25;
	}
yy151:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy154;
	default:	goto yy25;
	}
yy152:
	yych = *++cursor;
	switch (yych) {
	case 0x00:	goto yy155;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy25;
	case 'T':
	case 't':	goto yy159;
	default:	goto yy158;
	}
yy153:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy160;
	default:	goto yy25;
	}
yy154:
	yych = *++cursor;
	if (yych <= 0x00) goto yy161;
	goto yy25;
yy155:
	++cursor;
#line 92 "implicit.re"
	{   return (yaml_char_t *)"timestamp#ymd"; }
#line 1105 "implicit.c"
yy157:
	++cursor;
	yych = *cursor;
yy158:
	switch (yych) {
	case '\t':
	case ' ':	goto yy157;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy163;
	default:	goto yy25;
	}
yy159:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy164;
	default:	goto yy25;
	}
yy160:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy165;
	default:	goto yy25;
	}
yy161:
	++cursor;
#line 74 "implicit.re"
	{   return (yaml_char_t *)"int#na"; }
#line 1150 "implicit.c"
yy163:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy166;
	default:	goto yy25;
	}
yy164:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	default:	goto yy25;
	}
yy165:
	yych = *++cursor;
	if (yych <= 0x00) goto yy168;
	goto yy25;
yy166:
	yych = *++cursor;
	switch (yych) {
	case ':':	goto yy170;
	default:	goto yy25;
	}
yy167:
	yych = *++cursor;
	switch (yych) {
	case ':':	goto yy171;
	default:	goto yy25;
	}
yy168:
	++cursor;
#line 100 "implicit.re"
	{   return (yaml_char_t *)"str#na"; }
#line 1201 "implicit.c"
yy170:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy172;
	default:	goto yy25;
	}
yy171:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy173;
	default:	goto yy25;
	}
yy172:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy174;
	default:	goto yy25;
	}
yy173:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	default:	goto yy25;
	}
yy174:
	yych = *++cursor;
	switch (yych) {
	case ':':	goto yy176;
	default:	goto yy25;
	}
yy175:
	yych = *++cursor;
	switch (yych) {
	case ':':	goto yy177;
	default:	goto yy25;
	}
yy176:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy178;
	default:	goto yy25;
	}
yy177:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy179;
	default:	goto yy25;
	}
yy178:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy180;
	default:	goto yy25;
	}
yy179:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	default:	goto yy25;
	}
yy180:
	yych = *++cursor;
	switch (yych) {
	case '\t':
	case ' ':	goto yy182;
	case '.':	goto yy184;
	default:	goto yy25;
	}
yy181:
	yych = *++cursor;
	switch (yych) {
	case '.':	goto yy187;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy25;
	default:	goto yy188;
	}
yy182:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '\t':
	case ' ':	goto yy182;
	case '+':
	case '-':	goto yy190;
	case 'Z':	goto yy191;
	default:	goto yy25;
	}
yy184:
	++cursor;
	yych = *cursor;
	switch (yych) {
	case '\t':
	case ' ':	goto yy182;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy184;
	default:	goto yy25;
	}
yy186:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy192;
	default:	goto yy25;
	}
yy187:
	++cursor;
	yych = *cursor;
yy188:
	switch (yych) {
	case '+':
	case '-':	goto yy186;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy187;
	case 'Z':	goto yy189;
	default:	goto yy25;
	}
yy189:
	yych = *++cursor;
	if (yych <= 0x00) goto yy193;
	goto yy25;
yy190:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy195;
	default:	goto yy25;
	}
yy191:
	yych = *++cursor;
	if (yych <= 0x00) goto yy196;
	goto yy25;
yy192:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy198;
	default:	goto yy25;
	}
yy193:
	++cursor;
#line 94 "implicit.re"
	{   return (yaml_char_t *)"timestamp#iso8601"; }
#line 1464 "implicit.c"
yy195:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy199;
	default:	goto yy25;
	}
yy196:
	++cursor;
#line 96 "implicit.re"
	{   return (yaml_char_t *)"timestamp#spaced"; }
#line 1484 "implicit.c"
yy198:
	yych = *++cursor;
	switch (yych) {
	case 0x00:	goto yy193;
	case ':':	goto yy200;
	default:	goto yy25;
	}
yy199:
	yych = *++cursor;
	switch (yych) {
	case 0x00:	goto yy196;
	case ':':	goto yy201;
	default:	goto yy25;
	}
yy200:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy202;
	default:	goto yy25;
	}
yy201:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy203;
	default:	goto yy25;
	}
yy202:
	yych = *++cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy189;
	default:	goto yy25;
	}
yy203:
	++cursor;
	switch ((yych = *cursor)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy191;
	default:	goto yy25;
	}
}
#line 108 "implicit.re"


}
